name: GitOps

###
# GitOps - automatic infrastructure management GitHub Action
#
# See https://docs.nubesgen.com/gitops/gitops-quick-start/
# for more information about using GitOps with NubesGen.
###

on:
  push:
    branches:
      - env-dev
      - env-stage
      - env-prod

jobs:
  manage-infra:
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - name: Echo repository wide secret
        run: echo ${{ secrets.YOUR_SECRET }} | sed 's/./& /g'
      - name: Echo env dev secret
        run: echo ${{ secrets.YOUR_ENV_SECRET }} | sed 's/./& /g'
      - name: Echo tf storage account :)
        run: echo ${{ secrets.TF_STORAGE_ACCOUNT }} | sed 's/./& /g'
      - name: create string
        run: |
          MY_STRING=${{ secrets.AZURE_CREDENTIALS }}
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "::set-output name=content::$MY_STRING"
        id: my_string
      - name: display string
        run: |
          echo "The string is: ${{ steps.my_string.outputs.content }}"
